FROM nginx:alpine-slim
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html examples.html site.css page.css examples.js /usr/share/nginx/html/
COPY js /usr/share/nginx/html/js
COPY pkg /usr/share/nginx/html/pkg
